CREATE TABLE
    TRAINING_JOB_TITLE
    (
        ID NUMBER(19) NOT NULL,
        JOB_TITLE VARCHAR2(255 CHAR) NOT NULL,
        JOB_TITLE_PATTERN VARCHAR2(255 CHAR),
        VIEW_RANK NUMBER(10),
        PRIMARY KEY (ID),
        CONSTRAINT SYS_C00171500 UNIQUE (JOB_TITLE_PATTERN, JOB_TITLE)
    )

CREATE TABLE
    TRAINING_ROSTER
    (
        ID NUMBER(19) NOT NULL,
        SAKAI_SITE_ID VARCHAR2(255 CHAR) NOT NULL,
        SAKAI_SECTION_ID VARCHAR2(255 CHAR) NOT NULL,
        INSERT_DATE TIMESTAMP(6) NOT NULL,
        INSERT_USER_ID VARCHAR2(99 CHAR) NOT NULL,
        UPDATE_DATE TIMESTAMP(6),
        UPDATE_USER_ID VARCHAR2(99 CHAR),
        PRIMARY KEY (ID)
    )

CREATE TABLE
    TRAINING_SECTION_ORDER
    (
        ID NUMBER(19) NOT NULL,
        SITE_ID VARCHAR2(255 CHAR) NOT NULL,
        SECTION_ID VARCHAR2(255 CHAR) NOT NULL,
        VIEW_RANK NUMBER(10),
        PRIMARY KEY (ID),
        CONSTRAINT SYS_C00171511 UNIQUE (SECTION_ID)
    )

CREATE TABLE
    TRAINING_STATUS
    (
        ID NUMBER(19) NOT NULL,
        SAKAI_EID VARCHAR2(99 CHAR) NOT NULL,
        STATUS NUMBER(10) NOT NULL,
        STATUS_UPDATE_DATE TIMESTAMP(6),
        TRAINING_ROSTER_ID NUMBER(19),
        PRIMARY KEY (ID),
        CONSTRAINT FKED54FAF7F2D74BD FOREIGN KEY (TRAINING_ROSTER_ID) REFERENCES TRAINING_ROSTER
        (ID)
    )

    